import AppKit
@testable import FluidVoice_Debug
import XCTest

/// Verifies that temporary Cmd+V payloads are tagged so clipboard managers exclude them
/// from history while the plain-text representation remains available to the paste target.
@MainActor
final class TypingServiceTransientPasteboardTests: XCTestCase {
    func testTemporaryPasteboardWriteCarriesText() {
        let pasteboard = self.makePasteboard()
        defer { pasteboard.releaseGlobally() }

        XCTAssertTrue(
            SystemPasteboardManager(pasteboard: pasteboard)
                .writeTemporaryText("hello world", sessionID: "session")
        )
        XCTAssertEqual(pasteboard.string(forType: .string), "hello world")
    }

    func testTemporaryPasteboardWriteIsMarkedForClipboardManagers() throws {
        let pasteboard = self.makePasteboard()
        defer { pasteboard.releaseGlobally() }

        XCTAssertTrue(
            SystemPasteboardManager(pasteboard: pasteboard)
                .writeTemporaryText("hello world", sessionID: "session")
        )
        let item = try XCTUnwrap(pasteboard.pasteboardItems?.first)
        let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
        let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
        let types = item.types.map(\.rawValue)
        XCTAssertTrue(
            types.contains(transientType.rawValue),
            "temporary write must be marked Transient so clipboard managers skip it"
        )
        XCTAssertTrue(
            types.contains(autoGeneratedType.rawValue),
            "temporary write must be marked AutoGenerated so clipboard managers skip it"
        )
        XCTAssertEqual(
            item.data(forType: transientType)?.count,
            0
        )
        XCTAssertEqual(
            item.data(forType: autoGeneratedType)?.count,
            0
        )
    }

    func testTemporaryPasteboardWriteCarriesSourceAndSession() throws {
        let pasteboard = self.makePasteboard()
        defer { pasteboard.releaseGlobally() }

        XCTAssertTrue(
            SystemPasteboardManager(pasteboard: pasteboard)
                .writeTemporaryText("hello world", sessionID: "session")
        )
        let item = try XCTUnwrap(pasteboard.pasteboardItems?.first)
        let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")
        let sessionType = NSPasteboard.PasteboardType(
            "\(Bundle.main.bundleIdentifier ?? "com.FluidApp.Fluid").PasteSession"
        )
        XCTAssertEqual(item.string(forType: sourceType), Bundle.main.bundleIdentifier ?? "com.FluidApp.Fluid")
        XCTAssertEqual(item.string(forType: sessionType), "session")
    }

    func testTemporaryPasteboardWriteIsNotMarkedConcealed() throws {
        let pasteboard = self.makePasteboard()
        defer { pasteboard.releaseGlobally() }

        XCTAssertTrue(
            SystemPasteboardManager(pasteboard: pasteboard)
                .writeTemporaryText("hello world", sessionID: "session")
        )
        let item = try XCTUnwrap(pasteboard.pasteboardItems?.first)
        let types = item.types.map(\.rawValue)
        XCTAssertFalse(
            types.contains("org.nspasteboard.ConcealedType"),
            "ConcealedType signals sensitive content and must not be applied to a transcript"
        )
    }

    func testRecoveryActivationDoesNotRaiseAllWindowsOfTargetApp() {
        // Issue #748: recovery must NOT raise every window of the target app.
        let options = TypingService.recoveryActivationOptions

        XCTAssertTrue(
            options.contains(.activateIgnoringOtherApps),
            "recovery must still activate the target app and bring it forward"
        )
        XCTAssertFalse(
            options.contains(.activateAllWindows),
            "Recovery must not raise every window of the target app (issue #748)"
        )
    }

    func testIntentionalClipboardWriteIsHistoryVisible() throws {
        let pasteboard = self.makePasteboard()
        defer { pasteboard.releaseGlobally() }

        XCTAssertTrue(SystemPasteboardManager(pasteboard: pasteboard).writeIntentionalText("keep me"))

        let item = try XCTUnwrap(pasteboard.pasteboardItems?.first)
        let types = item.types.map(\.rawValue)
        XCTAssertEqual(item.string(forType: .string), "keep me")
        XCTAssertFalse(types.contains("org.nspasteboard.TransientType"))
        XCTAssertFalse(types.contains("org.nspasteboard.AutoGeneratedType"))
        XCTAssertFalse(types.contains("org.nspasteboard.ConcealedType"))
        XCTAssertFalse(types.contains { $0.hasSuffix(".PasteSession") })
    }

    func testSnapshotRestoresEveryRepresentation() throws {
        let pasteboard = self.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        let customType = NSPasteboard.PasteboardType("com.fluidvoice.tests.custom")
        let customData = Data([0x01, 0x02, 0x03])
        let originalItem = NSPasteboardItem()
        XCTAssertTrue(originalItem.setString("original", forType: .string))
        XCTAssertTrue(originalItem.setData(customData, forType: customType))
        let secondItem = NSPasteboardItem()
        XCTAssertTrue(secondItem.setString("second", forType: .string))
        XCTAssertTrue(pasteboard.writeObjects([originalItem, secondItem]))
        let originalItems = try XCTUnwrap(pasteboard.pasteboardItems)
        let originalTypes = originalItems.map(\.types)
        let originalRepresentations = originalItems.map { item in
            item.types.map { type in item.data(forType: type) }
        }

        let manager = SystemPasteboardManager(pasteboard: pasteboard)
        let snapshot = try XCTUnwrap(manager.captureSnapshot())
        XCTAssertTrue(manager.writeTemporaryText("temporary", sessionID: "session"))
        XCTAssertTrue(manager.restore(snapshot))

        let restoredItems = try XCTUnwrap(pasteboard.pasteboardItems)
        XCTAssertEqual(restoredItems.count, 2)
        for (restoredItem, sourceTypes) in zip(restoredItems, originalTypes) {
            XCTAssertEqual(Array(restoredItem.types.prefix(sourceTypes.count)), sourceTypes)
            XCTAssertTrue(restoredItem.types.contains(Self.transientType))
            XCTAssertTrue(restoredItem.types.contains(Self.autoGeneratedType))
        }
        XCTAssertEqual(
            zip(restoredItems, originalTypes).map { item, types in
                types.map { type in item.data(forType: type) }
            },
            originalRepresentations
        )
        let restoredItem = restoredItems[0]
        XCTAssertEqual(restoredItem.string(forType: .string), "original")
        XCTAssertEqual(restoredItem.data(forType: customType), customData)
        XCTAssertEqual(restoredItems[1].string(forType: .string), "second")
    }

    func testSnapshotRestoresImageBeforeTextInOriginalPreferenceOrder() throws {
        let pasteboard = self.makePasteboard()
        defer { pasteboard.releaseGlobally() }

        let bitmap = try XCTUnwrap(
            NSBitmapImageRep(
                bitmapDataPlanes: nil,
                pixelsWide: 2,
                pixelsHigh: 2,
                bitsPerSample: 8,
                samplesPerPixel: 4,
                hasAlpha: true,
                isPlanar: false,
                colorSpaceName: .deviceRGB,
                bytesPerRow: 0,
                bitsPerPixel: 0
            )
        )
        bitmap.setColor(NSColor(deviceRed: 0, green: 0, blue: 1, alpha: 1), atX: 0, y: 0)
        bitmap.setColor(NSColor(deviceRed: 1, green: 0, blue: 0, alpha: 1), atX: 1, y: 0)
        bitmap.setColor(NSColor(deviceRed: 0, green: 1, blue: 0, alpha: 1), atX: 0, y: 1)
        bitmap.setColor(NSColor(deviceRed: 1, green: 1, blue: 1, alpha: 1), atX: 1, y: 1)
        let imageData = try XCTUnwrap(bitmap.representation(using: .tiff, properties: [:]))
        let originalItem = NSPasteboardItem()
        XCTAssertTrue(originalItem.setData(imageData, forType: .tiff))
        XCTAssertTrue(originalItem.setString("image text fallback", forType: .string))
        XCTAssertTrue(pasteboard.writeObjects([originalItem]))
        let originalTypes = try XCTUnwrap(pasteboard.pasteboardItems?.first?.types)
        XCTAssertEqual(originalTypes.first, .tiff)

        let manager = SystemPasteboardManager(pasteboard: pasteboard)
        let snapshot = try XCTUnwrap(manager.captureSnapshot())
        XCTAssertEqual(snapshot.items.first?.representations.map(\.type), originalTypes)
        XCTAssertTrue(manager.writeTemporaryText("temporary", sessionID: "session"))
        XCTAssertTrue(manager.restore(snapshot))

        let restoredItem = try XCTUnwrap(pasteboard.pasteboardItems?.first)
        XCTAssertEqual(Array(restoredItem.types.prefix(originalTypes.count)), originalTypes)
        XCTAssertEqual(restoredItem.data(forType: .tiff), imageData)
        XCTAssertEqual(restoredItem.string(forType: .string), "image text fallback")
        let restoredImageData = try XCTUnwrap(restoredItem.data(forType: .tiff))
        XCTAssertNotNil(NSImage(data: restoredImageData))
    }

    func testSnapshotAddsPortableImageBeforeFilenameForICNSOnlyClipboard() throws {
        let pasteboard = self.makePasteboard()
        defer { pasteboard.releaseGlobally() }

        let bitmap = try XCTUnwrap(
            NSBitmapImageRep(
                bitmapDataPlanes: nil,
                pixelsWide: 2,
                pixelsHigh: 2,
                bitsPerSample: 8,
                samplesPerPixel: 4,
                hasAlpha: true,
                isPlanar: false,
                colorSpaceName: .deviceRGB,
                bytesPerRow: 0,
                bitsPerPixel: 0
            )
        )
        bitmap.setColor(NSColor(deviceRed: 0, green: 0, blue: 1, alpha: 1), atX: 0, y: 0)
        let sourceImageData = try XCTUnwrap(bitmap.representation(using: .png, properties: [:]))
        let icnsType = NSPasteboard.PasteboardType("com.apple.icns")
        let originalItem = NSPasteboardItem()
        XCTAssertTrue(originalItem.setString("Example.icns", forType: .string))
        XCTAssertTrue(originalItem.setData(sourceImageData, forType: icnsType))
        XCTAssertTrue(pasteboard.writeObjects([originalItem]))

        let manager = SystemPasteboardManager(pasteboard: pasteboard)
        let snapshot = try XCTUnwrap(manager.captureSnapshot())
        XCTAssertNotNil(snapshot.items.first?.portableImage)
        XCTAssertTrue(manager.writeTemporaryText("temporary", sessionID: "session"))
        XCTAssertTrue(manager.restore(snapshot))

        let externalReader = NSPasteboard(name: pasteboard.name)
        let restoredItem = try XCTUnwrap(externalReader.pasteboardItems?.first)
        XCTAssertEqual(restoredItem.types.first, .png)
        XCTAssertEqual(restoredItem.string(forType: .string), "Example.icns")
        XCTAssertEqual(restoredItem.data(forType: icnsType), sourceImageData)
        XCTAssertNotNil(restoredItem.data(forType: .png).flatMap(NSImage.init(data:)))
        XCTAssertTrue(restoredItem.types.contains(Self.transientType))
        XCTAssertTrue(restoredItem.types.contains(Self.autoGeneratedType))
    }

    func testSnapshotAddsPortableImageForImageFileURL() throws {
        let pasteboard = self.makePasteboard()
        defer { pasteboard.releaseGlobally() }

        let temporaryDirectory = FileManager.default.temporaryDirectory
            .appendingPathComponent("fluidvoice-image-pasteboard-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: temporaryDirectory, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: temporaryDirectory) }

        let bitmap = try XCTUnwrap(
            NSBitmapImageRep(
                bitmapDataPlanes: nil,
                pixelsWide: 1,
                pixelsHigh: 1,
                bitsPerSample: 8,
                samplesPerPixel: 4,
                hasAlpha: true,
                isPlanar: false,
                colorSpaceName: .deviceRGB,
                bytesPerRow: 0,
                bitsPerPixel: 0
            )
        )
        bitmap.setColor(NSColor(deviceRed: 1, green: 0, blue: 0, alpha: 1), atX: 0, y: 0)
        let sourceImageData = try XCTUnwrap(bitmap.representation(using: .png, properties: [:]))
        let imageURL = temporaryDirectory.appendingPathComponent("Example.png")
        try sourceImageData.write(to: imageURL)

        bitmap.setColor(NSColor(deviceRed: 0, green: 0, blue: 1, alpha: 1), atX: 0, y: 0)
        let iconData = try XCTUnwrap(bitmap.representation(using: .png, properties: [:]))
        let icnsType = NSPasteboard.PasteboardType("com.apple.icns")
        let originalItem = NSPasteboardItem()
        XCTAssertTrue(originalItem.setString(imageURL.absoluteString, forType: .fileURL))
        XCTAssertTrue(originalItem.setString("Example.png", forType: .string))
        XCTAssertTrue(originalItem.setData(iconData, forType: icnsType))
        XCTAssertTrue(pasteboard.writeObjects([originalItem]))

        let manager = SystemPasteboardManager(pasteboard: pasteboard)
        let snapshot = try XCTUnwrap(manager.captureSnapshot())
        XCTAssertNotNil(snapshot.items.first?.portableImage)
        XCTAssertTrue(manager.writeTemporaryText("temporary", sessionID: "session"))
        XCTAssertTrue(manager.restore(snapshot))

        let restoredItem = try XCTUnwrap(pasteboard.pasteboardItems?.first)
        XCTAssertEqual(Array(restoredItem.types.prefix(2)), [.fileURL, .png])
        XCTAssertEqual(restoredItem.string(forType: .fileURL), imageURL.absoluteString)
        XCTAssertEqual(restoredItem.data(forType: icnsType), iconData)
        XCTAssertNotEqual(restoredItem.data(forType: .png), iconData)
        XCTAssertEqual(restoredItem.data(forType: .png), sourceImageData)

        let restoredPNG = try XCTUnwrap(restoredItem.data(forType: .png))
        let restoredBitmap = try XCTUnwrap(NSBitmapImageRep(data: restoredPNG))
        let restoredColor = try XCTUnwrap(restoredBitmap.colorAt(x: 0, y: 0)?.usingColorSpace(.deviceRGB))
        XCTAssertGreaterThan(restoredColor.redComponent, 0.8)
        XCTAssertGreaterThan(restoredColor.redComponent, restoredColor.greenComponent + 0.5)
        XCTAssertGreaterThan(restoredColor.redComponent, restoredColor.blueComponent + 0.5)
    }

    func testSnapshotUsesEmbeddedImageWhenImageFileURLCannotBeRead() throws {
        let pasteboard = self.makePasteboard()
        defer { pasteboard.releaseGlobally() }

        let bitmap = try XCTUnwrap(
            NSBitmapImageRep(
                bitmapDataPlanes: nil,
                pixelsWide: 1,
                pixelsHigh: 1,
                bitsPerSample: 8,
                samplesPerPixel: 4,
                hasAlpha: true,
                isPlanar: false,
                colorSpaceName: .deviceRGB,
                bytesPerRow: 0,
                bitsPerPixel: 0
            )
        )
        let iconData = try XCTUnwrap(bitmap.representation(using: .png, properties: [:]))
        let icnsType = NSPasteboard.PasteboardType("com.apple.icns")
        let originalItem = NSPasteboardItem()
        XCTAssertTrue(originalItem.setString("file:///.file/id=123456.789", forType: .fileURL))
        XCTAssertTrue(originalItem.setString("Example.png", forType: .string))
        XCTAssertTrue(originalItem.setData(iconData, forType: icnsType))
        XCTAssertTrue(pasteboard.writeObjects([originalItem]))

        let manager = SystemPasteboardManager(pasteboard: pasteboard)
        let snapshot = try XCTUnwrap(manager.captureSnapshot())
        XCTAssertNotNil(snapshot.items.first?.portableImage)
        XCTAssertTrue(manager.writeTemporaryText("temporary", sessionID: "session"))
        XCTAssertTrue(manager.restore(snapshot))

        let externalReader = NSPasteboard(name: pasteboard.name)
        let restoredItem = try XCTUnwrap(externalReader.pasteboardItems?.first)
        XCTAssertTrue(restoredItem.types.contains(.png))
        XCTAssertLessThan(
            try XCTUnwrap(restoredItem.types.firstIndex(of: .png)),
            try XCTUnwrap(restoredItem.types.firstIndex(of: .string))
        )
        XCTAssertNotNil(restoredItem.data(forType: .png).flatMap(NSImage.init(data:)))
    }

    func testSnapshotDoesNotTurnNonImageFileIconIntoImage() throws {
        let pasteboard = self.makePasteboard()
        defer { pasteboard.releaseGlobally() }

        let bitmap = try XCTUnwrap(
            NSBitmapImageRep(
                bitmapDataPlanes: nil,
                pixelsWide: 1,
                pixelsHigh: 1,
                bitsPerSample: 8,
                samplesPerPixel: 4,
                hasAlpha: true,
                isPlanar: false,
                colorSpaceName: .deviceRGB,
                bytesPerRow: 0,
                bitsPerPixel: 0
            )
        )
        let iconData = try XCTUnwrap(bitmap.representation(using: .png, properties: [:]))
        let icnsType = NSPasteboard.PasteboardType("com.apple.icns")
        let originalItem = NSPasteboardItem()
        XCTAssertTrue(originalItem.setString("file:///tmp/Example.txt", forType: .fileURL))
        XCTAssertTrue(originalItem.setString("Example.txt", forType: .string))
        XCTAssertTrue(originalItem.setData(iconData, forType: icnsType))
        XCTAssertTrue(pasteboard.writeObjects([originalItem]))

        let manager = SystemPasteboardManager(pasteboard: pasteboard)
        let snapshot = try XCTUnwrap(manager.captureSnapshot())
        XCTAssertTrue(manager.writeTemporaryText("temporary", sessionID: "session"))
        XCTAssertTrue(manager.restore(snapshot))

        let restoredItem = try XCTUnwrap(pasteboard.pasteboardItems?.first)
        XCTAssertFalse(restoredItem.types.contains(.png))
        XCTAssertEqual(restoredItem.string(forType: .fileURL), "file:///tmp/Example.txt")
        XCTAssertEqual(restoredItem.data(forType: icnsType), iconData)
    }

    func testLargeRepresentationIsSnapshottedAndRestoredWithoutSizeLimit() throws {
        let pasteboard = self.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        let customType = NSPasteboard.PasteboardType("com.fluidvoice.tests.large")
        let originalData = Data(repeating: 0xab, count: 20 * 1024 * 1024)
        let originalItem = NSPasteboardItem()
        XCTAssertTrue(originalItem.setData(originalData, forType: customType))
        XCTAssertTrue(pasteboard.writeObjects([originalItem]))

        let manager = SystemPasteboardManager(pasteboard: pasteboard)
        let snapshot = try XCTUnwrap(manager.captureSnapshot())
        XCTAssertEqual(snapshot.items.first?.representations.first?.data, originalData)
        XCTAssertTrue(manager.writeTemporaryText("temporary", sessionID: "session"))
        XCTAssertTrue(manager.restore(snapshot))

        XCTAssertEqual(pasteboard.data(forType: customType), originalData)
    }

    func testMoreThanOneHundredItemsAreSnapshottedAndRestored() throws {
        let pasteboard = self.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        let originalItems = (0..<101).map { index in
            let item = NSPasteboardItem()
            XCTAssertTrue(item.setString("item \(index)", forType: .string))
            return item
        }
        XCTAssertTrue(pasteboard.writeObjects(originalItems))

        let manager = SystemPasteboardManager(pasteboard: pasteboard)
        let snapshot = try XCTUnwrap(manager.captureSnapshot())
        XCTAssertEqual(snapshot.items.count, 101)
        XCTAssertTrue(manager.writeTemporaryText("temporary", sessionID: "session"))
        XCTAssertTrue(manager.restore(snapshot))

        let restoredItems = try XCTUnwrap(pasteboard.pasteboardItems)
        XCTAssertEqual(restoredItems.count, 101)
        XCTAssertEqual(restoredItems.first?.string(forType: .string), "item 0")
        XCTAssertEqual(restoredItems.last?.string(forType: .string), "item 100")
    }

    private func makePasteboard() -> NSPasteboard {
        let name = NSPasteboard.Name("com.fluidvoice.tests.transient.\(UUID().uuidString)")
        let pasteboard = NSPasteboard(name: name)
        pasteboard.clearContents()
        return pasteboard
    }

    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
}
