import AppKit
@testable import FluidVoice_Debug
import XCTest

// The temporary clipboard write used to drive synthetic Cmd+V must be tagged so clipboard
// managers exclude it from history. It is restored immediately and is not user-copied content.
final class TypingServiceTransientPasteboardTests: XCTestCase {

    func testTransientPasteboardItem_carriesText() {
        let item = TypingService.makeTransientPasteboardItem("hello world")
        XCTAssertEqual(
            item.string(forType: .string),
            "hello world",
            "the plain string must survive so paste and clipboard restore behave unchanged"
        )
    }

    func testTransientPasteboardItem_isMarkedForClipboardManagers() {
        let item = TypingService.makeTransientPasteboardItem("hello world")
        let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
        let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
        let types = item.types.map(\.rawValue)
        XCTAssertTrue(
            types.contains(transientType.rawValue),
            "temporary write must be marked Transient so clipboard managers skip it"
        )
        XCTAssertTrue(
            types.contains(autoGeneratedType.rawValue),
            "temporary write must be marked AutoGenerated so clipboard managers skip it"
        )
        XCTAssertEqual(
            item.data(forType: transientType)?.count,
            0
        )
        XCTAssertEqual(
            item.data(forType: autoGeneratedType)?.count,
            0
        )
    }

    func testTransientMarkersSurvivePasteboardWrite() throws {
        let name = NSPasteboard.Name("com.fluidvoice.tests.transient.\(UUID().uuidString)")
        let pasteboard = NSPasteboard(name: name)
        defer { pasteboard.releaseGlobally() }

        pasteboard.clearContents()
        XCTAssertTrue(
            pasteboard.writeObjects([TypingService.makeTransientPasteboardItem("hello world")])
        )

        let item = try XCTUnwrap(pasteboard.pasteboardItems?.first)
        let types = item.types.map(\.rawValue)
        XCTAssertEqual(item.string(forType: .string), "hello world")
        XCTAssertTrue(types.contains("org.nspasteboard.TransientType"))
        XCTAssertTrue(types.contains("org.nspasteboard.AutoGeneratedType"))
    }

    func testTransientPasteboardItem_isNotMarkedConcealed() {
        let item = TypingService.makeTransientPasteboardItem("hello world")
        let types = item.types.map(\.rawValue)
        XCTAssertFalse(
            types.contains("org.nspasteboard.ConcealedType"),
            "ConcealedType signals sensitive content and must not be applied to a transcript"
        )
    }

    func testFocusRestoreDoesNotRaiseAllWindowsOfTargetApp() {
        // Issue #748: restoring focus after dictation must NOT raise every window of the
        // target app. `.activateAllWindows` brings forward all windows of the process and
        // destroys a multi-window layout (e.g. WebStorm) on every dictation.
        let options = TypingService.focusRestoreActivationOptions

        XCTAssertTrue(
            options.contains(.activateIgnoringOtherApps),
            "focus restore must still activate the target app and bring it forward"
        )
        XCTAssertFalse(
            options.contains(.activateAllWindows),
            "Restoring focus must not raise every window of the target app (issue #748)"
        )
    }

    func testFocusedTextSnapshotWithoutVerifiableChannelShortCircuitsVerification() {
        // A GPU-rendered / terminal target (e.g. Ghostty) exposes no verifiable accessibility
        // text value and no text-field selected range: all four channels are nil, so the
        // snapshot cannot be verified and `waitForFocusedTextVerification` must short-circuit to
        // `.unavailable` instead of polling the full 5 s `timeoutMicros` while the process-global
        // pasteboard session semaphore is held.
        XCTAssertFalse(
            TypingService.focusedTextSnapshotSupportsVerification(
                value: nil,
                selectedRange: nil,
                appScriptValue: nil,
                appScriptSelectedRange: nil
            ),
            "a snapshot whose four verifiable channels are all nil must be unverifiable"
        )

        // Any single non-nil channel is enough to make the snapshot verifiable, so a verifiable
        // target (e.g. CotEditor, Notes, Xcode) keeps its current fast-path behaviour.
        XCTAssertTrue(
            TypingService.focusedTextSnapshotSupportsVerification(
                value: "hello",
                selectedRange: nil,
                appScriptValue: nil,
                appScriptSelectedRange: nil
            ),
            "a non-nil accessibility text value makes the snapshot verifiable"
        )

        XCTAssertTrue(
            TypingService.focusedTextSnapshotSupportsVerification(
                value: nil,
                selectedRange: nil,
                appScriptValue: "hello",
                appScriptSelectedRange: nil
            ),
            "a non-nil AppleScript text value makes the snapshot verifiable"
        )

        XCTAssertTrue(
            TypingService.focusedTextSnapshotSupportsVerification(
                value: nil,
                selectedRange: CFRange(location: 0, length: 0),
                appScriptValue: nil,
                appScriptSelectedRange: nil
            ),
            "a non-nil selected range makes the snapshot verifiable"
        )
    }

    func testWaitForFocusedTextVerificationShortCircuitsUnverifiableTargetInBoundedTime() {
        // Behavioral coverage of the #802 fix: a target whose snapshot has a real pid but all four
        // verifiable channels nil (a GPU-rendered terminal such as Ghostty) must short-circuit to
        // `.unavailable` after a bounded pasteboard-consume window — NOT poll the full
        // `timeoutMicros`. This is an assertion-level guard, not a compile-time one: remove the
        // short-circuit from `waitForFocusedTextVerification` and this returns `.timeout` after
        // ~`timeoutMicros`, failing both asserts below. The short-circuit path is deterministic
        // (it never reads live AX state and does not touch the pasteboard session semaphore), so it
        // is safe to drive headlessly; the verifiable poll loop is not, so it is not exercised here.
        let typing = TypingService()
        let snapshot = TypingService.FocusedTextSnapshot(
            pid: 1,
            bundleIdentifier: nil,
            value: nil,
            selectedRange: nil,
            appScriptValue: nil,
            appScriptSelectedRange: nil
        )
        let timeoutMicros: useconds_t = 5_000_000

        let start = Date()
        let result = typing.waitForFocusedTextVerification(
            from: snapshot,
            expectedText: "hello",
            timeoutMicros: timeoutMicros
        )
        let elapsed = Date().timeIntervalSince(start)

        XCTAssertEqual(
            result,
            .unavailable,
            "an unverifiable target must short-circuit to .unavailable, not poll to .timeout"
        )
        // Well under `timeoutMicros` (5 s): proves the short-circuit did NOT poll the full window.
        // The bound is `timeoutMicros / 2`, so a loaded CI runner still clears it comfortably above
        // the ~0.5 s consume window, while a full ~5 s poll would blow straight past it.
        XCTAssertLessThan(
            elapsed,
            Double(timeoutMicros) / 1_000_000.0 / 2.0,
            "short-circuit must return well under timeoutMicros; took \(elapsed) s"
        )
    }
}
