import AppKit
import Carbon
import Foundation
import UniformTypeIdentifiers

enum TextDeliveryFailure: String, Equatable {
    case emptyText = "empty_text"
    case accessibilityNotTrusted = "accessibility_not_trusted"
    case clipboardSnapshotFailed = "clipboard_snapshot_failed"
    case clipboardWriteFailed = "clipboard_write_failed"
    case pasteCommandFailed = "paste_command_failed"
    case targetUnavailable = "target_unavailable"
    case targetRestoreFailed = "target_restore_failed"
}

enum TextDeliveryResult: Equatable {
    case commandPosted
    case recoverableFailure(TextDeliveryFailure)

    var wasDispatched: Bool {
        self == .commandPosted
    }
}

struct PasteboardSnapshot: Equatable {
    struct Item: Equatable {
        struct Representation: Equatable {
            let type: NSPasteboard.PasteboardType
            let data: Data
        }

        /// AppKit uses source order as representation preference, so this must remain ordered.
        let representations: [Representation]
        /// Materialized while the original owner still provides file access or promised image data.
        let portableImage: Representation?

        init(representations: [Representation], portableImage: Representation? = nil) {
            self.representations = representations
            self.portableImage = portableImage
        }
    }

    let items: [Item]
}

@MainActor
protocol PasteboardManaging: AnyObject {
    func captureSnapshot() -> PasteboardSnapshot?
    func writeTemporaryText(_ text: String, sessionID: String) -> Bool
    func writeIntentionalText(_ text: String) -> Bool
    func isOwned(sessionID: String, expectedText: String) -> Bool
    func restore(_ snapshot: PasteboardSnapshot) -> Bool
}

@MainActor
protocol PasteCommandPosting: AnyObject {
    func postGlobalPasteCommand() async -> Bool
}

@MainActor
final class SystemPasteboardManager: PasteboardManaging {
    private static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    private static let sessionType = NSPasteboard.PasteboardType(
        "\(Bundle.main.bundleIdentifier ?? "com.FluidApp.Fluid").PasteSession"
    )
    private static let fileSemanticTypes: Set<NSPasteboard.PasteboardType> = [
        .fileURL,
        NSPasteboard.PasteboardType("NSFilenamesPboardType"),
        NSPasteboard.PasteboardType("com.apple.pasteboard.promised-file-url"),
        NSPasteboard.PasteboardType("com.apple.pasteboard.promised-file-content-type"),
        NSPasteboard.PasteboardType("com.apple.filepromise"),
    ]

    private let pasteboard: NSPasteboard

    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
    }

    func captureSnapshot() -> PasteboardSnapshot? {
        let startedAt = ProcessInfo.processInfo.systemUptime
        for attempt in 1...2 {
            let startingChangeCount = self.pasteboard.changeCount
            guard let sourceItems = self.pasteboard.pasteboardItems else {
                let endingChangeCount = self.pasteboard.changeCount
                if endingChangeCount != startingChangeCount {
                    self.logSnapshotRetry(
                        attempt: attempt,
                        startingChangeCount: startingChangeCount,
                        endingChangeCount: endingChangeCount
                    )
                    continue
                }
                self.logSnapshotFailure(
                    reason: "pasteboard_items_unavailable",
                    itemCount: 0,
                    itemIndex: -1,
                    totalBytes: 0
                )
                return nil
            }
            var items: [PasteboardSnapshot.Item] = []
            var totalBytes = 0
            var totalPortableImageBytes = 0
            var totalRepresentations = 0
            var failure: (reason: String, itemIndex: Int, type: NSPasteboard.PasteboardType?)?

            itemLoop: for (itemIndex, sourceItem) in sourceItems.enumerated() {
                let sourceTypes = sourceItem.types
                guard !sourceTypes.isEmpty else {
                    failure = ("empty_item", itemIndex, nil)
                    break
                }

                var representations: [PasteboardSnapshot.Item.Representation] = []
                representations.reserveCapacity(sourceTypes.count)
                for type in sourceTypes {
                    guard let data = sourceItem.data(forType: type) else {
                        failure = ("unavailable_representation", itemIndex, type)
                        break itemLoop
                    }
                    representations.append(.init(type: type, data: data))
                    totalBytes += data.count
                    totalRepresentations += 1
                }
                let item = PasteboardSnapshot.Item(representations: representations)
                let portableImage = Self.portableImageRepresentation(for: item)
                totalPortableImageBytes += portableImage?.data.count ?? 0
                items.append(
                    .init(
                        representations: representations,
                        portableImage: portableImage
                    )
                )
            }

            let endingChangeCount = self.pasteboard.changeCount
            guard endingChangeCount == startingChangeCount else {
                self.logSnapshotRetry(
                    attempt: attempt,
                    startingChangeCount: startingChangeCount,
                    endingChangeCount: endingChangeCount
                )
                continue
            }

            if let failure {
                self.logSnapshotFailure(
                    reason: failure.reason,
                    itemCount: sourceItems.count,
                    itemIndex: failure.itemIndex,
                    totalBytes: totalBytes,
                    type: failure.type
                )
                return nil
            }

            self.log(
                "clipboard_snapshot_complete items=\(items.count) representations=\(totalRepresentations) " +
                    "bytes=\(totalBytes) portableImageBytes=\(totalPortableImageBytes) " +
                    "elapsedMs=\(Self.elapsedMs(since: startedAt)) firstItem=\(Self.representationSummary(items.first))"
            )
            return PasteboardSnapshot(items: items)
        }

        self.log("clipboard_snapshot_failed reason=clipboard_changed_during_snapshot")
        return nil
    }

    func writeTemporaryText(_ text: String, sessionID: String) -> Bool {
        let item = NSPasteboardItem()
        guard item.setString(text, forType: .string),
              item.setString(Bundle.main.bundleIdentifier ?? "com.FluidApp.Fluid", forType: Self.sourceType),
              item.setData(Data(), forType: Self.transientType),
              item.setData(Data(), forType: Self.autoGeneratedType),
              item.setString(sessionID, forType: Self.sessionType)
        else {
            return false
        }

        self.pasteboard.clearContents()
        return self.pasteboard.writeObjects([item]) && self.isOwned(sessionID: sessionID, expectedText: text)
    }

    func writeIntentionalText(_ text: String) -> Bool {
        let item = NSPasteboardItem()
        guard item.setString(text, forType: .string) else { return false }

        self.pasteboard.clearContents()
        return self.pasteboard.writeObjects([item]) && self.pasteboard.string(forType: .string) == text
    }

    func isOwned(sessionID: String, expectedText: String) -> Bool {
        self.pasteboard.string(forType: .string) == expectedText &&
            self.pasteboard.string(forType: Self.sessionType) == sessionID
    }

    func restore(_ snapshot: PasteboardSnapshot) -> Bool {
        var items: [NSPasteboardItem] = []
        for snapshotItem in snapshot.items {
            let item = NSPasteboardItem()
            let portableImage = snapshotItem.portableImage
            let hasFileURL = snapshotItem.representations.contains { $0.type == .fileURL }

            if !hasFileURL,
               let portableImage,
               !item.setData(portableImage.data, forType: portableImage.type)
            {
                self.log("clipboard_restore_failed reason=portable_image_write_failed type=\(portableImage.type.rawValue)")
                return false
            }
            for representation in snapshotItem.representations {
                guard Self.writeRestoredRepresentation(representation, to: item) else {
                    self.log("clipboard_restore_failed reason=representation_write_failed type=\(representation.type.rawValue)")
                    return false
                }
                if representation.type == .fileURL,
                   let portableImage,
                   !item.setData(portableImage.data, forType: portableImage.type)
                {
                    self.log("clipboard_restore_failed reason=portable_image_write_failed type=\(portableImage.type.rawValue)")
                    return false
                }
            }
            guard Self.addRestorationMarkers(to: item) else {
                self.log("clipboard_restore_failed reason=marker_write_failed")
                return false
            }
            items.append(item)
        }

        self.pasteboard.clearContents()
        guard items.isEmpty || self.pasteboard.writeObjects(items) else {
            self.log("clipboard_restore_failed reason=pasteboard_write_failed")
            return false
        }
        guard self.containsRestoredSnapshot(snapshot) else {
            self.log("clipboard_restore_failed reason=post_write_verification_failed")
            return false
        }

        let fileURLFallbacks = zip(self.pasteboard.pasteboardItems ?? [], snapshot.items).reduce(into: 0) { count, pair in
            let (restoredItem, snapshotItem) = pair
            if snapshotItem.representations.contains(where: { $0.type == .fileURL }),
               restoredItem.data(forType: .fileURL) == nil,
               snapshotItem.portableImage != nil
            {
                count += 1
            }
        }
        self.log(
            "clipboard_restore_verified items=\(snapshot.items.count) changeCount=\(self.pasteboard.changeCount) fileURLFallbacks=\(fileURLFallbacks) firstItem=\(Self.representationSummary(snapshot.items.first))"
        )
        if let portableImage = snapshot.items.first?.portableImage {
            self.log("clipboard_restore_portable_image type=\(portableImage.type.rawValue) bytes=\(portableImage.data.count)")
        }
        return true
    }

    private func containsRestoredSnapshot(_ snapshot: PasteboardSnapshot) -> Bool {
        let restoredItems = self.pasteboard.pasteboardItems ?? []
        guard restoredItems.count == snapshot.items.count else { return false }

        for (restoredItem, snapshotItem) in zip(restoredItems, snapshot.items) {
            for representation in snapshotItem.representations {
                if representation.type == .fileURL,
                   restoredItem.data(forType: .fileURL) == nil,
                   snapshotItem.portableImage != nil
                {
                    continue
                }
                guard Self.restoredData(restoredItem, matches: representation) else {
                    return false
                }
            }
            if let portableImage = snapshotItem.portableImage,
               restoredItem.data(forType: portableImage.type) != portableImage.data
            {
                return false
            }
            guard restoredItem.types.contains(Self.transientType),
                  restoredItem.types.contains(Self.autoGeneratedType)
            else {
                return false
            }
        }
        return true
    }

    private static func restoredData(
        _ restoredItem: NSPasteboardItem,
        matches representation: PasteboardSnapshot.Item.Representation
    ) -> Bool {
        if representation.type == .fileURL,
           let expectedURL = URL(dataRepresentation: representation.data, relativeTo: nil, isAbsolute: true),
           let restoredURL = restoredItem.string(forType: .fileURL).flatMap(URL.init(string:))
        {
            return restoredURL == expectedURL
        }
        return restoredItem.data(forType: representation.type) == representation.data
    }

    private static func portableImageRepresentation(
        for item: PasteboardSnapshot.Item
    ) -> PasteboardSnapshot.Item.Representation? {
        let sourceTypes = Set(item.representations.map(\.type))
        guard !sourceTypes.contains(.png),
              !sourceTypes.contains(.tiff)
        else {
            return nil
        }

        if !sourceTypes.isDisjoint(with: Self.fileSemanticTypes) {
            guard Self.fileItemContainsImage(item) else { return nil }

            // Preserve an image file's encoded bytes directly. Decoding and re-encoding it
            // here would put work proportional to its pixel count on the paste critical path.
            if let fileURL = Self.fileURL(in: item),
               let fileType = UTType(filenameExtension: fileURL.pathExtension),
               fileType.conforms(to: .image),
               let imageData = try? Data(contentsOf: fileURL, options: .mappedIfSafe)
            {
                return .init(
                    type: NSPasteboard.PasteboardType(fileType.identifier),
                    data: imageData
                )
            }
        }

        for representation in item.representations {
            guard UTType(representation.type.rawValue)?.conforms(to: .image) == true,
                  let pngData = Self.pngData(from: representation.data)
            else {
                continue
            }
            return .init(type: .png, data: pngData)
        }
        return nil
    }

    private static func fileItemContainsImage(_ item: PasteboardSnapshot.Item) -> Bool {
        if let fileURL = fileURL(in: item),
           isImageFilename(fileURL.lastPathComponent)
        {
            return true
        }

        guard let textRepresentation = item.representations.first(where: { $0.type == .string }),
              let filename = String(data: textRepresentation.data, encoding: .utf8)
        else {
            return false
        }
        return Self.isImageFilename(filename)
    }

    private static func fileURL(in item: PasteboardSnapshot.Item) -> URL? {
        guard let representation = item.representations.first(where: { $0.type == .fileURL }) else {
            return nil
        }
        return URL(dataRepresentation: representation.data, relativeTo: nil, isAbsolute: true)
    }

    private static func isImageFilename(_ filename: String) -> Bool {
        let pathExtension = (filename as NSString).pathExtension
        return !pathExtension.isEmpty && UTType(filenameExtension: pathExtension)?.conforms(to: .image) == true
    }

    private static func writeRestoredRepresentation(
        _ representation: PasteboardSnapshot.Item.Representation,
        to item: NSPasteboardItem
    ) -> Bool {
        if representation.type == .fileURL,
           let fileURL = URL(dataRepresentation: representation.data, relativeTo: nil, isAbsolute: true)
        {
            // A file URL is a semantic pasteboard property-list value. Re-emitting its
            // opaque bytes can appear valid to this process while disappearing for readers.
            return item.setString(fileURL.absoluteString, forType: .fileURL)
        }
        return item.setData(representation.data, forType: representation.type)
    }

    private static func pngData(from sourceData: Data) -> Data? {
        if let bitmap = NSBitmapImageRep(data: sourceData) {
            return bitmap.representation(using: .png, properties: [:])
        }

        guard let image = NSImage(data: sourceData) else { return nil }
        return Self.pngData(from: image)
    }

    private static func pngData(from image: NSImage) -> Data? {
        var proposedRect = NSRect(origin: .zero, size: image.size)
        guard let cgImage = image.cgImage(
            forProposedRect: &proposedRect,
            context: nil,
            hints: nil
        ) else {
            return nil
        }
        return NSBitmapImageRep(cgImage: cgImage).representation(using: .png, properties: [:])
    }

    private static func addRestorationMarkers(to item: NSPasteboardItem) -> Bool {
        let transientWasWritten = item.types.contains(Self.transientType) ||
            item.setData(Data(), forType: Self.transientType)
        let autoGeneratedWasWritten = item.types.contains(Self.autoGeneratedType) ||
            item.setData(Data(), forType: Self.autoGeneratedType)
        return transientWasWritten && autoGeneratedWasWritten
    }

    private static func representationSummary(_ item: PasteboardSnapshot.Item?) -> String {
        guard let item else { return "none" }
        return item.representations
            .map { "\($0.type.rawValue):\($0.data.count)" }
            .joined(separator: ",")
    }

    private func logSnapshotFailure(
        reason: String,
        itemCount: Int,
        itemIndex: Int,
        totalBytes: Int,
        type: NSPasteboard.PasteboardType? = nil
    ) {
        self.log(
            "clipboard_snapshot_failed reason=\(reason) items=\(itemCount) itemIndex=\(itemIndex) bytes=\(totalBytes) type=\(type?.rawValue ?? "nil")"
        )
    }

    private func logSnapshotRetry(
        attempt: Int,
        startingChangeCount: Int,
        endingChangeCount: Int
    ) {
        self.log(
            "clipboard_snapshot_retry attempt=\(attempt) startChangeCount=\(startingChangeCount) endChangeCount=\(endingChangeCount)"
        )
    }

    private func log(_ message: String) {
        DebugLogger.shared.benchmark("TYPING_BENCH", message: message, source: "TypingBenchmark")
    }

    private static func elapsedMs(since start: TimeInterval) -> Int {
        Int(((ProcessInfo.processInfo.systemUptime - start) * 1000).rounded())
    }
}

@MainActor
enum KeyboardLayoutKeyCodeResolver {
    static func keyCode(for character: Character, qwertyFallback: CGKeyCode) -> CGKeyCode {
        guard let source = TISCopyCurrentKeyboardLayoutInputSource()?.takeRetainedValue(),
              let rawLayoutData = TISGetInputSourceProperty(source, kTISPropertyUnicodeKeyLayoutData)
        else {
            return qwertyFallback
        }

        let layoutData = Unmanaged<CFData>.fromOpaque(rawLayoutData).takeUnretainedValue() as Data
        return layoutData.withUnsafeBytes { buffer in
            guard let layout = buffer.baseAddress?.assumingMemoryBound(to: UCKeyboardLayout.self) else {
                return qwertyFallback
            }
            return self.keyCode(for: character, qwertyFallback: qwertyFallback) { keyCode in
                self.unmodifiedScalar(for: keyCode, layout: layout)
            }
        }
    }

    static func keyCode(
        for character: Character,
        qwertyFallback: CGKeyCode,
        translatedScalar: (CGKeyCode) -> Unicode.Scalar?
    ) -> CGKeyCode {
        guard let targetScalar = character.unicodeScalars.first else { return qwertyFallback }

        for keyCode: CGKeyCode in 0..<128 where translatedScalar(keyCode) == targetScalar {
            return keyCode
        }
        return qwertyFallback
    }

    private static func unmodifiedScalar(
        for keyCode: CGKeyCode,
        layout: UnsafePointer<UCKeyboardLayout>
    ) -> Unicode.Scalar? {
        var deadKeyState: UInt32 = 0
        var characters = [UniChar](repeating: 0, count: 4)
        var length = 0
        let status = UCKeyTranslate(
            layout,
            keyCode,
            UInt16(kUCKeyActionDisplay),
            0,
            UInt32(LMGetKbdType()),
            UInt32(kUCKeyTranslateNoDeadKeysMask),
            &deadKeyState,
            characters.count,
            &length,
            &characters
        )
        guard status == noErr, length > 0 else { return nil }
        return Unicode.Scalar(characters[0])
    }
}

@MainActor
final class SystemPasteCommandPoster: PasteCommandPosting {
    func postGlobalPasteCommand() async -> Bool {
        guard AXIsProcessTrusted() else { return false }

        let pasteKeyCode = KeyboardLayoutKeyCodeResolver.keyCode(for: "v", qwertyFallback: 0x09)
        let source = CGEventSource(stateID: .combinedSessionState)
        guard let vDown = CGEvent(
            keyboardEventSource: source,
            virtualKey: pasteKeyCode,
            keyDown: true
        ), let vUp = CGEvent(
            keyboardEventSource: source,
            virtualKey: pasteKeyCode,
            keyDown: false
        ) else {
            return false
        }

        vDown.flags = .maskCommand
        vUp.flags = .maskCommand

        // The coordinator verifies pasteboard ownership before reaching this point,
        // so the temporary item is ready to consume without an additional delay.
        vDown.post(tap: .cghidEventTap)
        vUp.post(tap: .cghidEventTap)
        return true
    }
}

@MainActor
final class PasteDeliveryCoordinator {
    static let shared = PasteDeliveryCoordinator()
    nonisolated static let defaultSettlementDelayNanoseconds: UInt64 = 500_000_000

    private struct ClipboardLease {
        let originalSnapshot: PasteboardSnapshot
        let sessionID: String
        let text: String
        let generation: UInt64
        let shouldKeepTranscript: Bool
        var settlementTask: Task<Void, Never>?
    }

    private let pasteboard: PasteboardManaging
    private let commandPoster: PasteCommandPosting
    private let settlementDelayNanoseconds: UInt64
    private var generation: UInt64 = 0
    private var lease: ClipboardLease?
    private var isDelivering = false
    private var deliveryWaiters: [CheckedContinuation<Void, Never>] = []

    init(
        pasteboard: PasteboardManaging? = nil,
        commandPoster: PasteCommandPosting? = nil,
        settlementDelayNanoseconds: UInt64 = PasteDeliveryCoordinator.defaultSettlementDelayNanoseconds
    ) {
        self.pasteboard = pasteboard ?? SystemPasteboardManager()
        self.commandPoster = commandPoster ?? SystemPasteCommandPoster()
        self.settlementDelayNanoseconds = settlementDelayNanoseconds
    }

    func deliver(
        _ text: String,
        preserveTranscriptOnClipboard: Bool,
        onCommandPosted: ((TimeInterval) -> Void)? = nil
    ) async -> TextDeliveryResult {
        await self.acquireDeliverySlot()
        defer { self.releaseDeliverySlot() }

        let startedAt = ProcessInfo.processInfo.systemUptime
        self.generation &+= 1
        let generation = self.generation
        self.lease?.settlementTask?.cancel()

        let originalSnapshot = self.captureOriginalSnapshotForNextDelivery()
        self.lease = nil

        guard let originalSnapshot else {
            self.log("delivery_failed generation=\(generation) reason=clipboard_snapshot_failed")
            return .recoverableFailure(.clipboardSnapshotFailed)
        }

        let sessionID = UUID().uuidString
        let writeStartedAt = ProcessInfo.processInfo.systemUptime
        guard self.pasteboard.writeTemporaryText(text, sessionID: sessionID) else {
            self.restoreAfterFailure(originalSnapshot, generation: generation, reason: "clipboard_write_failed")
            self.log("delivery_failed generation=\(generation) reason=clipboard_write_failed")
            return .recoverableFailure(.clipboardWriteFailed)
        }
        self.log(
            "clipboard_write generation=\(generation) elapsedMs=\(Self.elapsedMs(since: writeStartedAt))"
        )

        guard await self.commandPoster.postGlobalPasteCommand() else {
            self.restoreAfterFailure(originalSnapshot, generation: generation, reason: "paste_command_failed")
            self.log("delivery_failed generation=\(generation) reason=paste_command_failed")
            return .recoverableFailure(.pasteCommandFailed)
        }
        let commandPostedAt = ProcessInfo.processInfo.systemUptime
        onCommandPosted?(commandPostedAt)

        self.log(
            "command_posted generation=\(generation) totalMs=\(Self.elapsedMs(since: startedAt))"
        )

        self.lease = ClipboardLease(
            originalSnapshot: originalSnapshot,
            sessionID: sessionID,
            text: text,
            generation: generation,
            shouldKeepTranscript: preserveTranscriptOnClipboard,
            settlementTask: nil
        )
        self.scheduleSettlement(sessionID: sessionID, generation: generation)
        return .commandPosted
    }

    private func acquireDeliverySlot() async {
        guard self.isDelivering else {
            self.isDelivering = true
            return
        }

        await withCheckedContinuation { continuation in
            self.deliveryWaiters.append(continuation)
        }
    }

    private func releaseDeliverySlot() {
        guard !self.deliveryWaiters.isEmpty else {
            self.isDelivering = false
            return
        }

        self.deliveryWaiters.removeFirst().resume()
    }

    func runPendingSettlementForTesting() {
        guard let lease = self.lease else { return }
        lease.settlementTask?.cancel()
        self.settleIfCurrent(sessionID: lease.sessionID, generation: lease.generation)
    }

    private func scheduleSettlement(sessionID: String, generation: UInt64) {
        let settlementDelayNanoseconds = self.settlementDelayNanoseconds
        let task = Task { @MainActor [weak self] in
            try? await Task.sleep(nanoseconds: settlementDelayNanoseconds)
            guard !Task.isCancelled else { return }
            self?.settleIfCurrent(sessionID: sessionID, generation: generation)
        }
        self.lease?.settlementTask = task
        self.log("settlement_scheduled generation=\(generation) delayMs=\(settlementDelayNanoseconds / 1_000_000)")
    }

    private func settleIfCurrent(sessionID: String, generation: UInt64) {
        guard let lease = self.lease,
              lease.generation == generation,
              lease.sessionID == sessionID
        else {
            self.log("settlement_skipped generation=\(generation) reason=stale_generation")
            return
        }

        self.lease = nil
        guard self.pasteboard.isOwned(sessionID: sessionID, expectedText: lease.text) else {
            self.log("settlement_skipped generation=\(generation) reason=clipboard_changed")
            return
        }

        if lease.shouldKeepTranscript {
            let didWrite = self.pasteboard.writeIntentionalText(lease.text)
            self.log("intentional_copy_settled generation=\(generation) success=\(didWrite)")
        } else {
            let didRestore = self.pasteboard.restore(lease.originalSnapshot)
            self.log("restore_completed generation=\(generation) success=\(didRestore)")
        }
    }

    private func captureOriginalSnapshotForNextDelivery() -> PasteboardSnapshot? {
        if let lease = self.lease,
           self.pasteboard.isOwned(sessionID: lease.sessionID, expectedText: lease.text)
        {
            return lease.originalSnapshot
        }
        return self.pasteboard.captureSnapshot()
    }

    private func restoreAfterFailure(
        _ snapshot: PasteboardSnapshot,
        generation: UInt64,
        reason: String
    ) {
        let didRestore = self.pasteboard.restore(snapshot)
        self.log("failure_restore generation=\(generation) reason=\(reason) success=\(didRestore)")
    }

    private func log(_ message: String) {
        DebugLogger.shared.benchmark("TYPING_BENCH", message: message, source: "TypingBenchmark")
    }

    private static func elapsedMs(since start: TimeInterval) -> Int {
        Int(((ProcessInfo.processInfo.systemUptime - start) * 1000).rounded())
    }
}
